"""create_research_qa_table

Revision ID: 9925aba8d74d
Revises: f54c8137f0b5
Create Date: 2025-12-02 20:31:55.443026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9925aba8d74d'
down_revision: Union[str, Sequence[str], None] = 'f54c8137f0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_qa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_markdown', sa.Text(), nullable=False),
    sa.Column('used_source_ids', sa.JSON(), nullable=True),
    sa.Column('llm_usage', sa.JSON(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_qa_job_id'), 'research_qa', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_qa_job_id'), table_name='research_qa')
    op.drop_table('research_qa')
    # ### end Alembic commands ###
