"""create_research_trace_events_table

Revision ID: d6ef8be4a6d4
Revises: 83da3fa9b583
Create Date: 2025-11-27 14:55:05.002029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ef8be4a6d4'
down_revision: Union[str, Sequence[str], None] = '83da3fa9b583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_trace_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_trace_events_job_id'), 'research_trace_events', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_trace_events_job_id'), table_name='research_trace_events')
    op.drop_table('research_trace_events')
    # ### end Alembic commands ###
